remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
title: null
description: A place for projects by Tonkers Tinkers
show_downloads: false
google_analytics: G-LTY71E4NF4
name: luaphacim's site
github:
  is_project_page: false
